### ISSUE TITLE
Add heading configuration option and magnetometer/compass telemetry

### ISSUE THREAD

**Issue by blopa1961** [rotorflight/rotorflight-configurator#102]
The Matek M10Q-5883 connected to the G747-HELI provides both GPS and magnetometer/compass (via the QMC5883L).
The problem is that once the magnetometer is enabled (yes, it works!) it interferes with the G474's onboard gyros because Rotorflight takes the readings from both sensors and mixes them, which results in a total loss of heading.
For this reason, it is now necessary to add an option to select from where the heading reading comes from, either the G474's gyros or the QMC5883L compass, but not both.
Also, there's no option for magnetometer/compass telemetry in Rotorflight Configurator's receiver menu, only "heading" from the gyro (or maybe the mixed values). A new receiver telemetry item with FrSky's telemetry ID 0x084F could be added.
I know I repeated this issue in rotorflight-firmware, but obviously both configurator and firmware need to be updated for this to work.

**Comment by rotorflight** [comment]
Your configuration is probably wrong. With the compass, the heading should be more precise, not messed up.
