### ISSUE TITLE
Add Flyfun V5

### ISSUE THREAD

**Issue by ahmad-kassem** [rotorflight/rotorflight-configurator#105]
Can we change the line to ( Hobbywing V4 / FlyFun V5 ) because they use the same protocol and people sometimes get confused and select V5 for FlyFun. 

https://github.com/rotorflight/rotorflight-configurator/blob/fef146b9b5accd7d9bb10a49e8eb865d5c86ab23/src/js/tabs/motors.js#L25

**Comment by rotorflight** [comment]
I think you got it wrong way around.
The ESC is called FlyFun
https://www.hobbywing.com/en/products?id=34
And the V4 refers to the Platinum series.
So the text should actually say:
"Hobbywing Platinum V4 / FlyFun V5"
And the other line
"Hobbywinf Platinum V5"

**Comment by ahmad-kassem** [comment]
Yeah this is exactly what I was trying to explain.
