### ISSUE TITLE
HoTT ASCII telemetry (PID and other settings)

### ISSUE THREAD

**Issue by Ralfde** [rotorflight/rotorflight-configurator#108]
feature request:
HoTT telemetry (ASCII/text mode):
betaflight and inav does support the settings f.e. PIDs, which are also supported by OSD to be adjusted to be adjusted in the HoTT telemetry ASCII/text mode.
Why was this function canceled at rotorflight?
Could this function be added, please?

**Comment by AndersHoglund** [comment]
This is a firmware function, not RFC. 
HoTT Text mode CMS display port is included in firmware, it has not been "cancelled" or removed. If there is a problem with it, report as a firmware issue.

**Comment by Ralfde** [comment]
Thanks a lot for the answer.After activating the CMS function it workes.Am 31.10.24, 19:08 schrieb "Anders Höglund" ***@***.***>:

This is a firmware function, not RFC.
HoTT Text mode CMS display port is included in firmware, it has not been "cancelled" or removed. If there is a problem with it, report as a firmware issue.

**Comment by AndersHoglund** [comment]
OK, good. Then if you are happy, please close this issue.
/A

**Comment by Ralfde** [comment]
Thanks a lot for your help again.
