### ISSUE TITLE
USB/Serial Port connection issue - windows10 or 11 (Asian language version)

### ISSUE THREAD

**Issue by bulustar** [rotorflight/rotorflight-configurator#12]
Thank you for great works.

I had the connection issue with the latest RF configurator as BetaFlight and iNav.
https://github.com/betaflight/betaflight-configurator/issues/2691
https://github.com/betaflight/betaflight-configurator/issues/2878

I've just copied the nwjs-v0.61.0 to RF configurator installation folder,
and working perfectly.

Please consider this for next release.

**Comment by rotorflight** [comment]
Next snapshot will be using a newer NW.js

**Comment by rotorflight** [comment]
Should be fixed now, though no feedback received.
