### ISSUE TITLE
Pasting multiple lines with commas sometimes cuts off the last line

### ISSUE THREAD

**Issue by rburrow87** [rotorflight/rotorflight-configurator#165]
I've ran into this now and then when trying to paste multiple lines with commas in them. It has existed for a while now, not just in recent builds.

This only happens if I paste them into CLI, never when loading from file. It looks fine when it's pasted but when I press enter, it'll usually cut off the beginning of the last line as you can see below. If paste and apply one line at a time, it's fine.

![image](https://github.com/user-attachments/assets/2f9daed2-4dfc-4417-8415-2fd2f7f36f8b)

**Comment by rotorflight** [comment]
Yes there are limits how long the lines can be, and how fast data can be sent.
Clearly not working correctly.
