### ISSUE TITLE
Refactor Adjustments tab

### ISSUE THREAD

**Issue by rotorflight** [rotorflight/rotorflight-configurator#25]
The Adjustment function has been totally refactored, and is working very differently. The Adjustments tab needs a similar refactoring.

- Adjustment type dropbox
  - Stepped / Continuous
  - Maybe combine with OFF switch... Off / Stepped / Continuous
- Enable channel (like before)
  - Add "Always enabled" in the list
- Control channel 
  - New dropdown menu and an slider below the enable channel
  - Two ranges needed with stepped adjustment
  -  One range needed with continuous adjustment
- Step size field as before
- Min & max value as before
- Adjustment function as before

Show the resulting adjustment value!

**Comment by egonl** [comment]
@rotorflight Couple of questions:
- What should the OFF switch do?
- How would you implement 'Always enabled', could you give a CLI example?
- Would it be possible to use non-AUX channels as well? So you can adjust values with for example roll?

**Comment by rotorflight** [comment]
Job done
