### ISSUE TITLE
Series on how to setup Rotorflight needed?

### ISSUE THREAD

**Issue by Painless360** [rotorflight/rotorflight-configurator#67]
Hi, I am Painless360 on YouTube. 

I fly helis and a few viewers have asked for some detail on this project. I've had a look at the wiki and am impressed with the work to bring FBL systems that include a lot of the 'goodness' from Betaflight. There is not enough awareness of this project. 

Forgive me for sending the request like this, but  I was wondering if you liked the idea of collaborating on some videos on my channel to show users how to set it up, avoid the common problems and raise awareness of it? 

If so, please send me an email at lee@painless360.com

Again, sorry for reaching out like this. I couldn't find the lead developers name and contact details. 

Happy Flying!

Lee

**Comment by rotorflight** [comment]
Will contact you!
