### ISSUE TITLE
Support for NT 6.1

### ISSUE THREAD

**Issue by andika207** [rotorflight/rotorflight-configurator#76]
I have zero interest on W10 or other similar awful crap.
What is the latest release that supports Win7 x64 ?

**Comment by rotorflight** [comment]
Rotorflight 1.0.0 was the last release to support Win7.
But there were bugs in the NW.js framework, that was updated to v16 for 1.0.1.
This unfortunately dropped support for Win7.

**Comment by andika207** [comment]
ok. so you will not compile the configurator with a different framework.
the other FBL gyros still support even WinXP.
I will never buy the ROTORFLIGHT FlyDragon if they don't support their customers
I can't understand why are user guides not translated to english
